BEGIN;

CREATE TYPE gender_type AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE marital_status_type AS ENUM ('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'OTHER');
CREATE TYPE loan_decision_status AS ENUM ('PENDING', 'APPROVED', 'DENIED');
CREATE TYPE signature_status_type AS ENUM ('UNSIGNED', 'SIGNED');

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    phone VARCHAR(32) NOT NULL UNIQUE,
    residential_address TEXT NOT NULL,
    registration_address TEXT NOT NULL,
    gender gender_type NOT NULL,
    marital_status marital_status_type NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE passports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE
        REFERENCES clients (id) ON DELETE CASCADE,
    -- Store Russian internal-passport details in canonical form:
    -- series without spaces (4 digits), number (6 digits), department code NNN-NNN.
    series VARCHAR(4) NOT NULL CHECK (series ~ '^[0-9]{4}$'),
    number VARCHAR(6) NOT NULL CHECK (number ~ '^[0-9]{6}$'),
    department_code VARCHAR(7) NOT NULL
        CHECK (department_code ~ '^[0-9]{3}-[0-9]{3}$'),
    issued_by VARCHAR(255) NOT NULL,
    issue_date DATE NOT NULL CHECK (issue_date <= CURRENT_DATE),
    UNIQUE (series, number)
);

CREATE TABLE employments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL
        REFERENCES clients (id) ON DELETE CASCADE,
    employed_from DATE NOT NULL,
    employed_to DATE,
    position VARCHAR(255) NOT NULL,
    organization_name VARCHAR(255) NOT NULL,
    CHECK (employed_to IS NULL OR employed_to >= employed_from)
);

CREATE TABLE loan_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients (id),
    requested_amount NUMERIC(15, 2) NOT NULL CHECK (requested_amount > 0),
    purpose VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE
        REFERENCES loan_applications (id) ON DELETE CASCADE,
    status loan_decision_status NOT NULL DEFAULT 'PENDING',
    approved_amount NUMERIC(15, 2),
    term_months SMALLINT,
    decided_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (status = 'PENDING'
            AND approved_amount IS NULL
            AND term_months IS NULL
            AND decided_at IS NULL)
        OR
        (status = 'DENIED'
            AND approved_amount IS NULL
            AND term_months IS NULL
            AND decided_at IS NOT NULL)
        OR
        (status = 'APPROVED'
            AND approved_amount > 0
            AND term_months BETWEEN 1 AND 12
            AND decided_at IS NOT NULL)
    )
);

CREATE TABLE loan_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE
        REFERENCES loan_applications (id),
    decision_id BIGINT NOT NULL UNIQUE
        REFERENCES loan_decisions (id),
    agreement_number VARCHAR(64) NOT NULL UNIQUE,
    signature_status signature_status_type NOT NULL DEFAULT 'UNSIGNED',
    signed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (signature_status = 'UNSIGNED' AND signed_at IS NULL)
        OR
        (signature_status = 'SIGNED' AND signed_at IS NOT NULL)
    )
);

CREATE INDEX idx_clients_name
    ON clients (last_name, first_name, middle_name);
CREATE INDEX idx_employments_client_id
    ON employments (client_id);
CREATE INDEX idx_loan_applications_client_id
    ON loan_applications (client_id);
CREATE INDEX idx_loan_decisions_status
    ON loan_decisions (status);
CREATE INDEX idx_loan_agreements_signature_status
    ON loan_agreements (signature_status);

COMMIT;
