--liquibase formatted sql

--changeset axi:002-create-loan-tables
CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    phone VARCHAR(32) NOT NULL UNIQUE,
    residential_address TEXT NOT NULL,
    registration_address TEXT NOT NULL,
    gender gender_type NOT NULL,
    marital_status marital_status_type NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE passports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE
        REFERENCES clients (id) ON DELETE CASCADE,
    series VARCHAR(4) NOT NULL CHECK (series ~ '^[0-9]{4}$'),
    number VARCHAR(6) NOT NULL CHECK (number ~ '^[0-9]{6}$'),
    department_code VARCHAR(7) NOT NULL
        CHECK (department_code ~ '^[0-9]{3}-[0-9]{3}$'),
    issued_by VARCHAR(255) NOT NULL,
    issue_date DATE NOT NULL CHECK (issue_date <= CURRENT_DATE),
    UNIQUE (series, number)
);

CREATE TABLE employments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL
        REFERENCES clients (id) ON DELETE CASCADE,
    employed_from DATE NOT NULL,
    employed_to DATE,
    position VARCHAR(255) NOT NULL,
    organization_name VARCHAR(255) NOT NULL,
    CHECK (employed_to IS NULL OR employed_to >= employed_from)
);

CREATE TABLE loan_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients (id),
    requested_amount NUMERIC(15, 2) NOT NULL CHECK (requested_amount > 0),
    purpose VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan_decisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE
        REFERENCES loan_applications (id) ON DELETE CASCADE,
    status loan_decision_status NOT NULL DEFAULT 'PENDING',
    approved_amount NUMERIC(15, 2),
    term_months SMALLINT,
    decided_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (status = 'PENDING'
            AND approved_amount IS NULL
            AND term_months IS NULL
            AND decided_at IS NULL)
        OR
        (status = 'DENIED'
            AND approved_amount IS NULL
            AND term_months IS NULL
            AND decided_at IS NOT NULL)
        OR
        (status = 'APPROVED'
            AND approved_amount > 0
            AND term_months BETWEEN 1 AND 12
            AND decided_at IS NOT NULL)
    )
);

CREATE TABLE loan_agreements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL UNIQUE
        REFERENCES loan_applications (id),
    decision_id BIGINT NOT NULL UNIQUE
        REFERENCES loan_decisions (id),
    agreement_number VARCHAR(64) NOT NULL UNIQUE,
    signature_status signature_status_type NOT NULL DEFAULT 'UNSIGNED',
    signed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (signature_status = 'UNSIGNED' AND signed_at IS NULL)
        OR
        (signature_status = 'SIGNED' AND signed_at IS NOT NULL)
    )
);

--rollback DROP TABLE loan_agreements;
--rollback DROP TABLE loan_decisions;
--rollback DROP TABLE loan_applications;
--rollback DROP TABLE employments;
--rollback DROP TABLE passports;
--rollback DROP TABLE clients;
